#ddev-generated
# Simple template to demonstrate pinecone
services:
  pinecone:
    container_name: ddev-${DDEV_SITENAME}-pinecone
    image: busybox:stable
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
