# DDEV-Local Pinecone recipe file.
#ddev-generated
services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    container_name: ddev-${DDEV_SITENAME}-pinecone
    environment:
      PORT: 5080-5090
      PINECONE_HOST: $DDEV_HOSTNAME
      # This defines the host name the service should be accessible from. This
      # will be sitename.ddev.site.
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 5080-5090:5080-5090
      HTTPS_EXPOSE: 5080-5090:5080-5090
    restart: "no"
    expose:
      - "5080-5090"
    platform: linux/amd64
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    #healthcheck:
    #  test: ["CMD-SHELL", "curl --fail -s localhost:5081/index/"]
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
