# DDEV-Local Pinecone recipe file.
#ddev-generated
services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    container_name: ddev-${DDEV_SITENAME}-pinecone
    environment:
      PORT: 5081
      PINECONE_HOST: pinecone
      INDEX_TYPE: serverless
      VECTOR_TYPE: dense
      DIMENSION: 2
      METRIC: cosine
    restart: "no"
    expose:
      - "5081:5081"
    platform: linux/amd64
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    #healthcheck:
    #  test: ["CMD-SHELL", "curl --fail -s localhost:5081/index/"]
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
