# DDEV-Local pinecone recipe file.
#ddev-generated
services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    environment:
      PORT: 5080
      PINECONE_HOST: localhost
    expose:
      - "5080-6000:5080-6000"
    platform: linux/amd64
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
